### ISSUE TITLE
no response after clicking on mentors name?

### ISSUE THREAD

**Issue by tyeung2017** [facn2/judgement-day#41]
and there is a error log in terminal

Error: Failed to lookup view "results" in views directory "/Users/l/FACN/week8/judgement-day/src/views"
    at Function.render (/Users/l/FACN/week8/judgement-day/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/Users/l/FACN/week8/judgement-day/node_modules/express/lib/response.js:971:7)
    at renderQueries.updateCategoryScore (/Users/l/FACN/week8/judgement-day/src/controllers/results.js:20:12)
    at updateRespectiveScore (/Users/l/FACN/week8/judgement-day/src/queries/queries.js:67:19)
    at db.query (/Users/l/FACN/week8/judgement-day/src/queries/queries.js:46:16)
    at Query.client.query (/Users/l/FACN/week8/judgement-day/node_modules/pg-pool/index.js:262:18)
    at Query.handleReadyForQuery (/Users/l/FACN/week8/judgement-day/node_modules/pg/lib/query.js:126:10)
    at Connection.<anonymous> (/Users/l/FACN/week8/judgement-day/node_modules/pg/lib/client.js:166:19)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)

**Comment by m4v15** [comment]
I think this is a duplicate of #40 but can't tell cos you've added no description..
